import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Transaction } from '@/hooks/useTransactions';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { CalendarIcon } from 'lucide-react';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';

interface TransactionDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSave: (transaction: any) => void;
  transaction?: Transaction;
  isLoading?: boolean;
}

export const INCOME_CATEGORIES = [
  'Weekly Revenue',
  'Field Work Income',
  'Data Entry Income',
  'Audit Income',
  'Booklet Income',
  'Other Income'
];

export const EXPENSE_CATEGORIES = [
  'Payroll',
  'Operations',
  'Logistics',
  'Incentives',
  'Utilities',
  'Office Supplies',
  'Staff Support',
  'Other Expenses'
];

export const TransactionDialog = ({ open, onOpenChange, onSave, transaction, isLoading }: TransactionDialogProps) => {
  const [date, setDate] = useState<Date>();
  const [type, setType] = useState<'income' | 'expense'>('income');
  const [category, setCategory] = useState('');
  const [description, setDescription] = useState('');
  const [amount, setAmount] = useState('');
  const [notes, setNotes] = useState('');

  useEffect(() => {
    if (transaction) {
      setDate(new Date(transaction.date));
      setType(transaction.type);
      setCategory(transaction.category);
      setDescription(transaction.description);
      setAmount(transaction.amount.toString());
      setNotes(transaction.metadata?.notes || '');
    } else {
      setDate(new Date());
      setType('income');
      setCategory('');
      setDescription('');
      setAmount('');
      setNotes('');
    }
  }, [transaction, open]);

  const handleSubmit = () => {
    if (!date || !category || !description || !amount) return;

    const transactionData = {
      date: format(date, 'yyyy-MM-dd'),
      type,
      category,
      description,
      amount: parseFloat(amount),
      is_auto_generated: false,
      metadata: { notes }
    };

    onSave(transaction ? { id: transaction.id, updates: transactionData } : transactionData);
    onOpenChange(false);
  };

  const categories = type === 'income' ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;
  const isAutoGenerated = transaction?.is_auto_generated;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>{transaction ? 'Edit Transaction' : 'Add New Transaction'}</DialogTitle>
        </DialogHeader>

        {isAutoGenerated && (
          <div className="bg-warning/10 border border-warning text-warning-foreground p-3 rounded-md text-sm">
            This transaction was automatically generated. You can only edit the description and notes.
          </div>
        )}

        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label>Date</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button variant="outline" className={cn("w-full justify-start text-left font-normal", !date && "text-muted-foreground")} disabled={isAutoGenerated}>
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {date ? format(date, "PPP") : <span>Pick a date</span>}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar mode="single" selected={date} onSelect={setDate} initialFocus className="pointer-events-auto" />
              </PopoverContent>
            </Popover>
          </div>

          <div className="space-y-2">
            <Label>Type</Label>
            <Select value={type} onValueChange={(v: 'income' | 'expense') => setType(v)} disabled={isAutoGenerated}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="income">Income</SelectItem>
                <SelectItem value="expense">Expense</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label>Category</Label>
            <Select value={category} onValueChange={setCategory} disabled={isAutoGenerated}>
              <SelectTrigger>
                <SelectValue placeholder="Select category" />
              </SelectTrigger>
              <SelectContent>
                {categories.map(cat => (
                  <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label>Description</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Enter description" />
          </div>

          <div className="space-y-2">
            <Label>Amount (₦)</Label>
            <Input type="number" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0.00" disabled={isAutoGenerated} />
          </div>

          <div className="space-y-2">
            <Label>Notes (Optional)</Label>
            <Textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Additional notes..." rows={3} />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button onClick={handleSubmit} disabled={isLoading || !date || !category || !description || !amount}>
            {isLoading ? 'Saving...' : 'Save Transaction'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
